import turtle
import math
chieu_cao_tuong = int(input("Nhap sai tuong nha(100 tro len): "))
chieu_ngang_nha = chieu_cao_tuong * 2.5
chieu_ngang_cua = chieu_cao_tuong * 1/2
chieu_cao_cua   = chieu_cao_tuong * 3/4
chieu_cao_mai   = chieu_cao_tuong

chieu_cao_cay   = int(input("Nhap chieu cao cay 1: "))
chieu_cao_cay_2 = int(input("Nhap chieu cao cay 2: "))
sc = turtle.Screen()
nhan_screen = turtle.Turtle()
nhan_screen.pensize(2)


nhan_screen.penup()
nhan_screen.goto(- chieu_ngang_nha/2, 0)
nhan_screen.pendown()
nhan_screen.color("blue")                   
nhan_screen.forward(chieu_ngang_nha)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_tuong)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_ngang_nha)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_tuong)                    
nhan_screen.left(90)

#cua nha
nhan_screen.penup()
nhan_screen.goto(- chieu_ngang_cua/2, 0)
nhan_screen.pendown()                 
nhan_screen.forward(chieu_ngang_cua)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_cua)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_ngang_cua)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_cua)                    
nhan_screen.left(90)

#mai nha
nhan_screen.penup()
nhan_screen.goto(- chieu_ngang_nha/2, chieu_cao_tuong)
nhan_screen.pendown()
nhan_screen.left(45)           
nhan_screen.forward(chieu_cao_mai * math.sqrt(2))                    
nhan_screen.left(-90)
nhan_screen.forward(chieu_cao_mai * math.sqrt(2))
nhan_screen.left(45)           

#ve cay
#than cay co goc 80 do
nhan_screen.penup()
nhan_screen.goto(chieu_ngang_nha/2 + chieu_cao_cay /2, - chieu_cao_cay / 3)
nhan_screen.pendown()
nhan_screen.fillcolor("gray")
nhan_screen.begin_fill()
nhan_screen.forward(chieu_cao_cay / 10 + 2 * chieu_cao_cay *(2/5)/math.tan(math.pi*4/9))                   
nhan_screen.left(100)
nhan_screen.forward(chieu_cao_cay * (2/5)/math.sin(math.pi*4/9))                    
nhan_screen.left(80)
nhan_screen.forward(chieu_cao_cay / 10)                    
nhan_screen.left(80)
nhan_screen.forward(chieu_cao_cay * (2/5)/math.sin(math.pi*4/9))                    
nhan_screen.left(100)
nhan_screen.end_fill()
#vela1
nhan_screen.color("lightgreen")
nhan_screen.penup()
nhan_screen.forward((chieu_cao_cay / 10 + 2 * chieu_cao_cay *(2/5)/math.tan(math.pi*4/9))/2)
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_cay * 2/5)
nhan_screen.left(-90)
nhan_screen.pendown()
nhan_screen.fillcolor("darkgreen")
nhan_screen.begin_fill()
nhan_screen.forward((chieu_cao_cay/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward((chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward((chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward((chieu_cao_cay/2)/2)
nhan_screen.left(90)             
nhan_screen.end_fill()

#vela2
nhan_screen.penup()
nhan_screen.forward((chieu_cao_cay/2)/2)
nhan_screen.left(-90) 
nhan_screen.pendown()
nhan_screen.fillcolor("forestgreen")
nhan_screen.begin_fill()
nhan_screen.forward(0.7*(chieu_cao_cay/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward(0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward(0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward(0.7*(chieu_cao_cay/2)/2) 
nhan_screen.left(90)                    
nhan_screen.end_fill()

#vela3
nhan_screen.penup()
nhan_screen.forward(0.7*(chieu_cao_cay/2)/2)
nhan_screen.left(-90) 
nhan_screen.pendown()
nhan_screen.fillcolor("lightgreen")
nhan_screen.begin_fill()
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/2)                    
nhan_screen.end_fill()


#ve cay 2
#than cay co goc 80 do
nhan_screen.penup()
nhan_screen.goto(-(chieu_ngang_nha/2 + chieu_cao_cay_2 /2), - chieu_cao_cay_2 )
nhan_screen.pendown()
nhan_screen.color("gray")
nhan_screen.fillcolor("gray")
nhan_screen.begin_fill()
nhan_screen.forward(chieu_cao_cay_2 / 10 + 2 * chieu_cao_cay_2 *(2/5)/math.tan(math.pi*4/9))                   
nhan_screen.left(100)
nhan_screen.forward(chieu_cao_cay_2 * (2/5)/math.sin(math.pi*4/9))                    
nhan_screen.left(80)
nhan_screen.forward(chieu_cao_cay_2 / 10)                    
nhan_screen.left(80)
nhan_screen.forward(chieu_cao_cay_2 * (2/5)/math.sin(math.pi*4/9))                    
nhan_screen.left(100)
nhan_screen.end_fill()
#vela1
nhan_screen.color("lightgreen")
nhan_screen.penup()
nhan_screen.forward((chieu_cao_cay_2 / 10 + 2 * chieu_cao_cay_2 *(2/5)/math.tan(math.pi*4/9))/2)
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_cay_2 * 2/5)
nhan_screen.left(-90)
nhan_screen.pendown()
nhan_screen.fillcolor("darkgreen")
nhan_screen.begin_fill()
nhan_screen.forward((chieu_cao_cay_2/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward((chieu_cao_cay_2/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward((chieu_cao_cay_2/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward((chieu_cao_cay_2/2)/2)
nhan_screen.left(90)             
nhan_screen.end_fill()

#vela2
nhan_screen.penup()
nhan_screen.forward((chieu_cao_cay_2/2)/2)
nhan_screen.left(-90) 
nhan_screen.pendown()
nhan_screen.fillcolor("forestgreen")
nhan_screen.begin_fill()
nhan_screen.forward(0.7*(chieu_cao_cay_2/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward(0.7*(chieu_cao_cay_2/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward(0.7*(chieu_cao_cay_2/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward(0.7*(chieu_cao_cay_2/2)/2) 
nhan_screen.left(90)                    
nhan_screen.end_fill()

#vela3
nhan_screen.penup()
nhan_screen.forward(0.7*(chieu_cao_cay_2/2)/2)
nhan_screen.left(-90) 
nhan_screen.pendown()
nhan_screen.fillcolor("lightgreen")
nhan_screen.begin_fill()
nhan_screen.forward(0.7*0.7*(chieu_cao_cay_2/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay_2/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay_2/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay_2/2)/2)                    
nhan_screen.end_fill()

turtle.done()