import turtle
import math
chieu_cao_tuong = 100
chieu_ngang_nha = 80
chieu_ngang_cua = 30
chieu_cao_cua   = 50
chieu_cao_mai   = 40
khoang_cach_cua = 30
canh_cua        = 30
duong_kinh_mt   = 50
tia_sang        = 40
chieu_cao_cay   = 220

sc = turtle.Screen()
nhan_screen = turtle.Turtle()
nhan_screen.pensize(2)
turtle.bgcolor("aqua")

nhan_screen.penup()
nhan_screen.goto(-200,-200)
nhan_screen.pendown()
nhan_screen.color("black") 
nhan_screen.fillcolor("blue")
nhan_screen.begin_fill()       
nhan_screen.forward(chieu_ngang_nha)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_tuong)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_ngang_nha)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_tuong)                    
nhan_screen.left(90)
nhan_screen.end_fill()
#cua nha
nhan_screen.penup()
nhan_screen.fillcolor("lime")
nhan_screen.begin_fill()
nhan_screen.forward(chieu_ngang_nha/2 - chieu_ngang_cua/2)
nhan_screen.pendown()                 
nhan_screen.forward(chieu_ngang_cua)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_cua)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_ngang_cua)                    
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_cua)                    
nhan_screen.left(180)
nhan_screen.end_fill()
#mai nha
nhan_screen.penup()
nhan_screen.forward(chieu_cao_tuong)
nhan_screen.left(90)           
nhan_screen.forward(chieu_ngang_nha/2 - chieu_ngang_cua/2)
nhan_screen.left(180)
nhan_screen.pendown()
nhan_screen.fillcolor("deeppink")
nhan_screen.begin_fill()
nhan_screen.left(45)           
nhan_screen.forward(chieu_cao_mai * math.sqrt(2))                    
nhan_screen.left(-90)
nhan_screen.forward(chieu_cao_mai * math.sqrt(2))
nhan_screen.right(135)
nhan_screen.forward(chieu_ngang_nha)
nhan_screen.end_fill() 
#canh nha
nhan_screen.penup()
nhan_screen.left(180) 
nhan_screen.forward(chieu_ngang_nha)
nhan_screen.left(30)           
nhan_screen.pendown()
nhan_screen.fillcolor("yellow")
nhan_screen.begin_fill()          
nhan_screen.forward(chieu_ngang_nha * math.sin(math.pi/3))                    
nhan_screen.left(-120)
nhan_screen.forward(chieu_cao_tuong)
nhan_screen.right(60)
nhan_screen.forward(chieu_ngang_nha * math.sin(math.pi/3))
nhan_screen.right(120) 
nhan_screen.forward(chieu_cao_tuong)
nhan_screen.end_fill() 
#cua so
nhan_screen.penup()
nhan_screen.right(180) 
nhan_screen.forward(khoang_cach_cua)
nhan_screen.left(120)
nhan_screen.forward(khoang_cach_cua* math.sin(math.pi/3))         
nhan_screen.pendown()
nhan_screen.fillcolor("brown")
nhan_screen.begin_fill()          
nhan_screen.forward(canh_cua * math.sin(math.pi/3))                    
nhan_screen.left(-120)
nhan_screen.forward(canh_cua)
nhan_screen.right(60)
nhan_screen.forward(canh_cua * math.sin(math.pi/3))
nhan_screen.right(120) 
nhan_screen.forward(canh_cua)
nhan_screen.end_fill()
#canh mai nha
nhan_screen.penup() 
nhan_screen.forward(khoang_cach_cua)
nhan_screen.left(120)
nhan_screen.forward(khoang_cach_cua* math.sin(math.pi/3))
nhan_screen.right(75)    
nhan_screen.pendown()
nhan_screen.fillcolor("orange")
nhan_screen.begin_fill()          
nhan_screen.forward(chieu_cao_mai * math.sqrt(2))                    
nhan_screen.right(105)
nhan_screen.forward(chieu_ngang_nha * math.sin(math.pi/3))
nhan_screen.right(75)
nhan_screen.forward(chieu_cao_mai * math.sqrt(2))
nhan_screen.right(105) 
nhan_screen.forward(chieu_ngang_nha * math.sin(math.pi/3))
nhan_screen.end_fill()
nhan_screen.left(150) 

#ve cay
#than cay co goc 80 do
nhan_screen.penup()
nhan_screen.goto(chieu_cao_cay *2/3, - chieu_cao_cay *4/5 )
nhan_screen.pendown()
nhan_screen.fillcolor("gray")
nhan_screen.begin_fill()
nhan_screen.forward(chieu_cao_cay / 10 + 2 * chieu_cao_cay *(2/5)/math.tan(math.pi*4/9))                   
nhan_screen.left(100)
nhan_screen.forward(chieu_cao_cay * (2/5)/math.sin(math.pi*4/9))                    
nhan_screen.left(80)
nhan_screen.forward(chieu_cao_cay / 10)                    
nhan_screen.left(80)
nhan_screen.forward(chieu_cao_cay * (2/5)/math.sin(math.pi*4/9))                    
nhan_screen.left(100)
nhan_screen.end_fill()
#vela1
nhan_screen.color("lightgreen")
nhan_screen.penup()
nhan_screen.forward((chieu_cao_cay / 10 + 2 * chieu_cao_cay *(2/5)/math.tan(math.pi*4/9))/2)
nhan_screen.left(90)
nhan_screen.forward(chieu_cao_cay * 2/5)
nhan_screen.left(-90)
nhan_screen.pendown()
nhan_screen.fillcolor("darkgreen")
nhan_screen.begin_fill()
nhan_screen.forward((chieu_cao_cay/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward((chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward((chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward((chieu_cao_cay/2)/2)
nhan_screen.left(90)             
nhan_screen.end_fill()

#vela2
nhan_screen.penup()
nhan_screen.forward((chieu_cao_cay/2)/2)
nhan_screen.left(-90) 
nhan_screen.pendown()
nhan_screen.fillcolor("forestgreen")
nhan_screen.begin_fill()
nhan_screen.forward(0.7*(chieu_cao_cay/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward(0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward(0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward(0.7*(chieu_cao_cay/2)/2) 
nhan_screen.left(90)                    
nhan_screen.end_fill()

#vela3
nhan_screen.penup()
nhan_screen.forward(0.7*(chieu_cao_cay/2)/2)
nhan_screen.left(-90) 
nhan_screen.pendown()
nhan_screen.fillcolor("lightgreen")
nhan_screen.begin_fill()
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/2)                   
nhan_screen.left(135)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(90)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/math.sqrt(2))                    
nhan_screen.left(135)
nhan_screen.forward(0.7*0.7*(chieu_cao_cay/2)/2)                    
nhan_screen.end_fill()

#ve mat troi
nhan_screen.penup()
nhan_screen.goto(duong_kinh_mt, duong_kinh_mt *3)
nhan_screen.pendown()
nhan_screen.color("black")
nhan_screen.fillcolor("yellow")
nhan_screen.begin_fill()
nhan_screen.circle(duong_kinh_mt)
nhan_screen.end_fill()
#tia sang
nhan_screen.right(90)
nhan_screen.forward(tia_sang)
#tia 2
nhan_screen.penup()
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt)
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt + tia_sang)
nhan_screen.left(90)
nhan_screen.pendown()
nhan_screen.forward(tia_sang)
#tia 3
nhan_screen.penup()
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt)
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt + tia_sang)
nhan_screen.left(90)
nhan_screen.pendown()
nhan_screen.forward(tia_sang)
#tia 4
nhan_screen.penup()
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt)
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt + tia_sang)
nhan_screen.left(90)
nhan_screen.pendown()
nhan_screen.forward(tia_sang)
#tia 1.1
nhan_screen.penup()
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt/math.sqrt(2))
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt - duong_kinh_mt/math.sqrt(2) + tia_sang)
nhan_screen.left(135)
nhan_screen.pendown()
nhan_screen.forward(tia_sang *3/4)
#tia 1.2
nhan_screen.penup()
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt)
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt + tia_sang *3/4)
nhan_screen.left(90)
nhan_screen.pendown()
nhan_screen.forward(tia_sang *3/4)
#tia 1.3
nhan_screen.penup()
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt)
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt + tia_sang *3/4)
nhan_screen.left(90)
nhan_screen.pendown()
nhan_screen.forward(tia_sang *3/4)
#tia 1.4
nhan_screen.penup()
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt)
nhan_screen.right(90)
nhan_screen.forward(duong_kinh_mt + tia_sang *3/4)
nhan_screen.left(90)
nhan_screen.pendown()
nhan_screen.forward(tia_sang *3/4)

turtle.done()